display UI math magician
Mucyosoda/Math-Magician pull request #2
Opened 2021-11-02 18:17 UTC by Mucyosoda

Math Magicians app that will hold the core functionality: a calculator.

2021-11-02 18:33 UTC, helman101 requested changes
# STATUS: CHANGES REQUIRED ♻️ 🔴 

Hi @Mucyosoda 👋, 

Nice job so far with this project 😄, but there are still some changes to do.

## Required Changes ♻️

- [ ] _Check the comments under the review._

Cheers and Happy coding!👏👏👏

![gif](https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif)

If anything is not 100% clear please leave your questions or comments in the PR thread, we will be glad to help you 😄.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-02 18:33 UTC, helman101 commented on src/Components/calculator.js
> +const Calc = () => (
- [ ] This should be a class component instead of a functional one, kindly make this change 😄

2021-11-02 18:33 UTC, helman101 commented on src/App.js
> +const App = () => (
- [ ] This should be a class component instead of a functional one, kindly make this change 😄

2021-11-03 04:49 UTC, e71az approved these changes
## Status:  Approved 🟢

Hi, @Mucyosoda, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

![](https://media3.giphy.com/media/DnMMGxEvniha7CvASq/giphy.gif)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-05 09:23 UTC, merged