complete full website
Mucyosoda/Math-Magician pull request #6
Opened 2021-11-10 12:13 UTC by Mucyosoda

Math magician project is designed to solve basic math calculations and 
is built with different technology like React, CSS, babelrc, JavaScript, 
linters. The project is still under construction for next project.

2021-11-10 13:06 UTC, rloterh requested changes
Hi Mucyo, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦  🚦  

## Good Points 👍  
- No linter errors


## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Kindly check the comments marked **[OPTIONAL]** under the review._
<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-10 13:06 UTC, rloterh commented on src/index.css
>  body {
- [ ] Your component **import is not implemented correctly**. You have used capitalization for your component directory. Kindly ensure that your import corresponds with the appropriate directory.

**Import error:**
![image](https://user-images.githubusercontent.com/12745474/141116733-35c8bf2f-f512-45b1-8629-90559a445811.png)

2021-11-10 13:06 UTC, rloterh commented on src/index.css
>  body {
- [ ] OPTIONAL
Your **Pull Request** is indicating that `src/index.css` is the only file you worked on. Kindly endeavor to make the necessary _git commits_ for this project.

2021-11-10 16:01 UTC, Mucyosoda commented on src/index.css
>  body {
Hi rloterh,
Last week I worked on this project that is why it seemed like I have not changed, I have made changes on the quote page, welcome page, and styling files.

2021-11-10 20:38 UTC, Emmyn5600 requested changes
Hi, @Mucyosoda 

Good job so far! 👏🏼 

Great work on making the project requirements:clap:
You've done well implementing the project requirements, but there are still some issues which aren't been addressed yet 
 
## STATUS: CHANGES REQUESTED :recycle:


### Changes requested.

- [x] As requested by the previous reviewer, there are some issues to be solved before you merge. Your project is not running please fix it before you request another review.
![data-10](https://user-images.githubusercontent.com/55635977/141189596-57681060-ae24-4bf9-b3a4-e1bfe7c37ffa.png)

 #### Optional suggestions
 
 - N/A
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-11-11 15:41 UTC, D4nielJ commented
Hi @Mucyosoda, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't compile correctly, which has been pointed out by the others reviewers. Kindly fix this issue.

### Make sure that the name of your files are the same when you import them. Also, in React is a standard to name components with a Capital letter both in file and in the declaration. `Calculator.js` ---> `const Calculator = () => (...)`. When imported make sure to `import Calculator from 'Calculator'`

![image](https://user-images.githubusercontent.com/79114233/141325831-be581714-cf83-4606-8b20-6d393ae3b7ab.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-11-12 04:35 UTC, D4nielJ commented
Hi @Mucyosoda, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't address the issues pointed by the previous reviewers. Please make sure to fix these issues and ask for a new review once you are ready.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-11-12 16:22 UTC, GzimAsani approved these changes
# STATUS: APPROVED :100:         
## Thank you for implementing all the project requirements, you've done a great job :trophy: There is nothing else to say other than... it's time to merge it :champagne:  :tada: Congratulations

Cheers and Happy coding! :clap:  :computer:  :wine_glass: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-11-13 14:44 UTC, merged